name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Setup
        run: make install

      - name: Format
        run: make format

      - name: Lint
        run: make lint

      - name: Test
        run: make test

      - name: Generate and Push Markdown Report
        run: make generate_report

      # - name: Upload Markdown Report
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: markdown_report
      #     path: profile_report.md
